---
- name: Install prerequisites
  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
  tags: [ server ]

- name: Install LAMP Packages
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]
  tags: [ server ]
